<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

<title>ENT Sample Project</title>

<link href='http://fonts.googleapis.com/css?family=Maven+Pro:400' rel='stylesheet' type='text/css'>
<link href="<?php echo $this->url('app/design/css/app.css'); ?>" rel="stylesheet" type="text/css" />

<script type="text/javascript" src="<?php echo $this->url('scripts/jquery-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/jquery-ui-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/underscore-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/backbone.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/mustache-min.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->url('scripts/app.js'); ?>"></script>
