<!DOCTYPE HTML>
<html>
	<head>
		<?php echo $this->getChildElement('head'); ?>
	</head>
	<!--[if lt IE 7]><body class="ie ie6 lte9 lte8 lte7"><![endif]-->
	<!--[if IE 7]><body class="ie ie7 lte9 lte8 lte7"><![endif]-->
	<!--[if IE 8]><body class="ie ie8 lte9 lte8"><![endif]-->
	<!--[if IE 9]><body class="ie ie9 lte9"><![endif]-->
	<!--[if gt IE 9]><body><![endif]-->
	<!--[if !IE]><!--><body><!--<![endif]-->	
		<div id="page-wrapper">			
			<?php /*
			<?php echo $this->getChildElement('top'); ?>
			<?php echo $this->getChildElement('middle'); ?>
			<?php echo $this->getChildElement('bottom'); ?>
			*/ ?>
		</div>

		<script type="layout" id="main">
			<div id="page-content-wrapper">
				<div class="page-content">
					<div class="page-content-left">
						<div class="box">
							<div class="box-content list">
								list goes here
							</div>
						</div>
					</div>
					
					<div class="page-content-right">
						<div class="box">
							<div class="box-content">
								<div class="detail">
									detail goes here
								</div>

								
							</div>
						</div>

						<div class="box">
							<div class="box-content create">
								create goes here
							</div>
						</div>
					</div>
				</div>
			</div>
		</script>

		<script type="layout" id="detailed">
			<div id="page-content-wrapper">
				<div class="page-content">
					<div class="box">
						<div class="box-content detailed">
							detailed details goes here
						</div>
					</div>
				</div>
			</div>
		</script>

		<script type="template" id="list">
			<ul id="list">
				{{#links}}
				<li>
					<a rel="{{id}}" href="">
						{{title}}
					</a>
				</li>
				{{/links}}
			</ul>
		</script>

		<script type="template" id="detail">
			<div id="detail">
				<h2>{{title}}</h2>
				<h4>{{url}}</h4><br /><br />

				<a href="" class="show">Show details</a><br /><br />
				<a href="" class="remove">Remove</a>
			</div>
		</script>

		<script type="template" id="create">
			<form method="POST">
				<label>Title:</label><input type="text" name="title" /><br />
				<label>Link:</label><input type="text" name="url" />

				<div class="input-submit"><input type="submit" /></div>
			</div>
		</script>
		
		<?php echo $this->getChildElement('javascript'); ?>
	</body>
</html>
