<script type="text/javascript" src="<?php echo $this->url('scripts/jquery-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/jquery-ui-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/underscore-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/backbone.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/mustache-min.js'); ?>"></script>
<script type="text/javascript" src="<?php echo $this->url('scripts/layoutmanager.js'); ?>"></script>

<script type="text/javascript" src="<?php echo $this->url('scripts/application.js'); ?>"></script>
