<div id="page-content-wrapper">
	<div class="page-content">
		
	</div>
</div>

<script type="layout" id="list">
	<div class="page-content-left">
		<div class="box">
			<div class="box-frame"></div>
			<div class="box-content">
				<ul id="list">
					... list ...

				</ul>
			</div>
		</div>
	</div>
</script>

<script type="layout" id="detail">
	<div class="page-content-right">
		<div class="box">
			<div class="box-frame"></div>
			<div class="box-content">
				<div id="detail">
					... details ...
				</div>
			</div>
		</div>
	</div>
</script>

<!--<div id="page-content-frame"></div>
<div id="page-content">
	<div class="content">
		<?php echo $this->getChildElement('content'); ?>
	</div>
</div>-->
